export const FETCH_CURRENCY_RATES_FAILED = 'FETCH_CURRENCY_RATES_FAILED';
export const FETCH_CURRENCY_RATES_SUCCESS = 'FETCH_CURRENCY_RATES_SUCCESS';
export const FETCH_CURRENCY_RATES_LOADING = 'FETCH_CURRENCY_RATES_LOADING';

export const SET_CURRENCY_FROM = 'SET_CURRENCY_FROM';
export const SET_CURRENCY_TO = 'SET_CURRENCY_TO';
export const SET_VALUE_FROM = 'SET_VALUE_FROM';
export const SET_VALUE_TO = 'SET_VALUE_TO';
export const EXCHANGE_CURRENCY = 'EXCHANGE_CURRENCY';


